name: morning
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./start.py

    # env:
    #   APP_ID: ${{ secrets.APP_ID }}
    #   APP_SECRET: ${{ secrets.APP_SECRET }}
    #   TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
    #   USER_ID: ${{ secrets.USER_ID }}
    #   START_DATE: ${{ secrets.START_DATE }}
    #   BIRTHDAY: ${{ secrets.BIRTHDAY }}
    #   CITY: ${{ secrets.CITY }}


# 今天是{{date2.DATA}}了哦！
# 最爱老婆的{{demo.DATA}}
 
# 这是详细时间哦：{{date.DATA}}
# 老婆在:{{city.DATA}}呢。
# 今天是:{{weather.DATA}}，嘻嘻。
# 最低气温是:{{tempn.DATA}}
# 最高气温是:{{temp.DATA}}
# 老婆已经是个:{{live.DATA}}天的大宝宝了！
# 我们在一起:{{in.DATA}}天了哦！
 
# {{wd.DATA}}
# {{english.DATA}}